import { localBusinessSchema } from '../app/schema';

// Structured data, written by the build system from verified business data.
// Server component: no 'use client'. Do not edit this file.
export default function LocalBusinessSchema() {
  return (
    <script
      type="application/ld+json"
      dangerouslySetInnerHTML={{ __html: JSON.stringify(localBusinessSchema) }}
    />
  );
}
